### ISSUE TITLE
Torch not compiled with CUDA enabled [BUG]

### ISSUE THREAD

**Issue by KeiMuriKoe** [Sanster/lama-cleaner#278]
try to use cpu, in config everywhere picked cpu
![image](https://user-images.githubusercontent.com/106619492/231885990-592075d6-5e01-4591-bb45-4e96b6c491e3.png)

**Comment by Sanster** [comment]
Can you post your configuration file or start command?

**Comment by KeiMuriKoe** [comment]
Sure, but I tried to solve the problems on my own, and now I have a different error. I am also attaching the installer_config.json and start.bat files. 
![image](https://user-images.githubusercontent.com/106619492/232225346-ecaa241d-3138-459b-9931-28b4970b1153.png)
![image](https://user-images.githubusercontent.com/106619492/232225369-2434537c-0c85-4c1f-8082-833ea1c80386.png)
![image](https://user-images.githubusercontent.com/106619492/232225395-ad05cb97-b413-48ec-88de-2933547556f3.png)

**Comment by KeiMuriKoe** [comment]
also win_config.bat if you need it 
![image](https://user-images.githubusercontent.com/106619492/232225489-307f6b7d-b6dd-45fe-b4b3-9f5ad7589358.png)

**Comment by axzaxxaxaxax** [comment]
I have a similar error occurs after enabling "Enable interactive segmentation using Segment Anything".

**Comment by Sanster** [comment]
@KeiMuriKoe I noticed that your `interactive_seg_device` is set to cuda. Can you try switching it to cpu?

<img width="398" alt="image" src="https://user-images.githubusercontent.com/3998421/232260994-0c6eb978-d0d5-4ec9-a486-8b577961fd9b.png">

**Comment by Sanster** [comment]
@axzaxxaxaxax I forgot to change the default device of interactive_seg_device to CPU. For now, you can manually modify `installer_config.json` and set `interactive_seg_device` to`cpu`.

**Comment by axzaxxaxaxax** [comment]
> .`installer_config.json``interactive_seg_device``cpu`

Yes it works

**Comment by KeiMuriKoe** [comment]
Yes, everything is working now. Thank you very much. I apologize for the delayed response. You really helped.

**Comment by HikiNarou** [comment]
Excuse me guys, I'm experiencing the same thing but my problem is after I do “Segement Text” and want to clean the Image by clicking “Clean Image” and this is the error result... (the full error output is below).

`2025-04-22 00:24:18.621 | INFO     | modules.utils.inpainting:load_jit_model:110 - Loading model from: C:\Users\Lenovo\Downloads\Programs\Comic Translate (BEST)\models\inpainting\anime-manga-big-lama.pt
2025-04-22 00:24:19.350 | ERROR    | modules.utils.inpainting:handle_error:97 - Failed to load model C:\Users\Lenovo\Downloads\Programs\Comic Translate (BEST)\models\inpainting\anime-manga-big-lama.pt,please submit an issue at https://github.com/Sanster/lama-cleaner/issues and include a screenshot of the error:
Torch not compiled with CUDA enabled
An error occurred:
SystemExit: -1

Traceback:
Traceback (most recent call last):
  File "C:\Users\Lenovo\Downloads\Programs\Comic Translate (BEST)\modules\utils\inpainting.py", line 112, in load_jit_model
    model = torch.jit.load(model_path, map_location="cpu").to(device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Downloads\Programs\Comic Translate (BEST)\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1343, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Downloads\Programs\Comic Translate (BEST)\.venv\Lib\site-packages\torch\nn\modules\module.py", line 903, in _apply
    module._apply(fn)
  File "C:\Users\Lenovo\Downloads\Programs\Comic Translate (BEST)\.venv\Lib\site-packages\torch\nn\modules\module.py", line 903, in _apply
    module._apply(fn)
  File "C:\Users\Lenovo\Downloads\Programs\Comic Translate (BEST)\.venv\Lib\site-packages\torch\nn\modules\module.py", line 903, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "C:\Users\Lenovo\Downloads\Programs\Comic Translate (BEST)\.venv\Lib\site-packages\torch\nn\modules\module.py", line 930, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\Users\Lenovo\Downloads\Programs\Comic Translate (BEST)\.venv\Lib\site-packages\torch\nn\modules\module.py", line 1329, in convert
    return t.to(
           ^^^^^
  File "C:\Users\Lenovo\Downloads\Programs\Comic Translate (BEST)\.venv\Lib\site-packages\torch\cuda\__init__.py", line 310, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lenovo\Downloads\Programs\Comic Translate (BEST)\app\thread_worker.py", line 30, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Downloads\Programs\Comic Translate (BEST)\pipeline.py", line 94, in inpaint
    inpainted = self.manual_inpaint()
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Downloads\Programs\Comic Translate (BEST)\pipeline.py", line 78, in manual_inpaint
    self.inpainter_cache = InpainterClass(device)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Downloads\Programs\Comic Translate (BEST)\modules\inpainting\base.py", line 32, in __init__
    self.init_model(device, **kwargs)
  File "C:\Users\Lenovo\Downloads\Programs\Comic Translate (BEST)\modules\inpainting\lama.py", line 38, in init_model
    self.model = load_jit_model(LAMA_MODEL_URL, device, LAMA_MODEL_MD5).eval()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\Downloads\Programs\Comic Translate (BEST)\modules\utils\inpainting.py", line 114, in load_jit_model
    handle_error(model_path, model_md5, e)
  File "C:\Users\Lenovo\Downloads\Programs\Comic Translate (BEST)\modules\utils\inpainting.py", line 101, in handle_error
    exit(-1)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: -1`
