### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by ftk789** [Sanster/lama-cleaner#35]
![image](https://user-images.githubusercontent.com/57598907/162525993-c8b09666-ffa0-4db5-9bd8-8be92977f2b9.png)

**Comment by Sanster** [comment]
The torch version you installed does not support gpu, you can use lama cleaner with cpu: `python3 main.py --device=cpu`

**Comment by ftk789** [comment]
Thank you <3 , Seems like the Torch version i had was not for GPU'S as you said

**Comment by Red007Master** [comment]
> Thank you <3 , Seems like the Torch version i had was not for GPU'S as you said

how did you install CUDA compatible Torch?

**Comment by Jeslandor** [comment]
> how did you install CUDA compatible Torch?

Just in case someone else had the same problem I was able to solve it by uninstalling pytorch and installing the cuda version with the next steps:

1) pip uninstall torch
2) pip install "torch==1.11.0+cu113" --index https://download.pytorch.org/whl/cu113/
