### ISSUE TITLE
How to use SD1.5 on M1 Mac? (CUDA not available Error)

### ISSUE THREAD

**Issue by all4five** [Sanster/lama-cleaner#97]
At the end of the demo video you can see the usage of SD1.5.

When I try to start Lama with --model=SD1.5 I get the following errors regarding missing CUDA. 

`/Users/USER/miniconda3/lib/python3.9/site-packages/torch/amp/autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
/Users/USER/miniconda3/lib/python3.9/site-packages/torch/amp/autocast_mode.py:198: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
usage: lama-cleaner [-h] [--host HOST] [--port PORT]
                    [--model {lama,ldm,zits,mat,fcf,sd1.5,cv2}]
                    [--hf_access_token HF_ACCESS_TOKEN] [--sd-disable-nsfw]
                    [--sd-cpu-textencoder] [--sd-run-local]
                    [--device {cuda,cpu}] [--gui]
                    [--gui-size GUI_SIZE GUI_SIZE] [--input INPUT] [--debug]
lama-cleaner: error: argument --model: invalid choice: 'SD1.5' (choose from 'lama', 'ldm', 'zits', 'mat', 'fcf', 'sd1.5', 'cv2')`

What can I do to get it working? I already downloaded both checkpoint versions 1.5 pruned and 1.5pruned emaonly from hugging face. Can someone explain to me the next steps?

**Comment by Sanster** [comment]
For stable-diffusion model, you need to [accepting the terms to access](https://huggingface.co/runwayml/stable-diffusion-inpainting), and get an access token from here [huggingface access token](https://huggingface.co/docs/hub/security-tokens). Then start the server:

```bash
lama-cleaner --model=sd1.5 --device=cpu --hf_access_token=you_token
```

I haven't tested it on the m1 and not sure if it will work, good luck

**Comment by all4five** [comment]
`lama-cleaner --model=sd1.5 --device=cpu --hf_access_token=you_token`

Thank you! That helped to install everything! I can start a dream process but since it's only doing this with the CPU. One take takes about 4-5 minutes. 

https://replicate.com/blog/run-stable-diffusion-on-m1-mac

Here they used a virtualenvironment. Do you have any ideas how to set it up for lama as well?

**Comment by Sanster** [comment]
Install the virtualenvironment according to the guidelines in the blog, then you can install Lama Cleaner (pip3 install lama-cleaner) after `Activate the virtualenv`

**Comment by all4five** [comment]
Thanks I'll try

**Comment by all4five** [comment]
I'm nut sure, which blog you mean. I tried setting up the venv like this:

cd LamaCleaner
python3 -m pip install virtualenv

**Comment by Sanster** [comment]
Sorry for the annoying log, actually you can safely ignore that CUDA warning. 

After the first time you run `lama-cleaner --model=sd1.5 --device=cpu --hf_access_token=you_token`, you can remove `--hf_access_token`, and add `--run-sd-local` to start the server

```bash
lama-cleaner --model=sd1.5 --device=cpu --run-sd-local
```

**Comment by all4five** [comment]
Thank you. It's still giving me errors. Look at this 

![1](https://user-images.githubusercontent.com/113880578/197715422-eba317c1-31a7-47cb-b8c2-ea8e7b47714a.png)

With that it runs but slowly. 

After that I closed the terminal and started again with 

`lama-cleaner --model=sd1.5 --device=cpu --run-sd-local`

![2](https://user-images.githubusercontent.com/113880578/197716002-d6b155d7-f851-43f7-826b-7931399da0e2.png)

Somehow it does not recognize `--run-sd-local`

**Comment by Sanster** [comment]
> Sorry for the annoying log, actually you can safely ignore that CUDA warning.
> 
> After the first time you run `lama-cleaner --model=sd1.5 --device=cpu --hf_access_token=you_token`, you can remove `--hf_access_token`, and add `--run-sd-local` to start the server
> 
> ```shell
> lama-cleaner --model=sd1.5 --device=cpu --run-sd-local
> ```

I made a typo, it should be `--sd-run-local`. This parameter simply allows you to not pass the huggingface token, nothing to do with running speed.

![image](https://user-images.githubusercontent.com/3998421/197719036-188bc1cc-7d1f-493b-ae4a-4727700470fa.png)

You can ignore this CUDA warning, it is normal for this warning to appear on machines without NVIDIA graphics. 

The real reason the model running slow is, we should use PyTorch compiled for the M1 chip, currently Lama Cleaner not support that, I will add M1 support If I could get an M1 Mac.

**Comment by Sanster** [comment]
SIX MONTHS LATER....

Set `--device=mps` run fastest stable diffusion model on m1/m2 chip, on my m2 pro the speed is 1.5~2 it/s
